publisher_joint_trajectory_controller:
  ros__parameters:

    controller_name: "position_trajectory_controller"
    wait_sec_between_publish: 6

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1: [0.785, 0.5, 0.0, 0.785, 0.5, 0.0]
    pos2: [0,0,0,0,0,0 ]
    pos3: [-0.785, 0.5, 0.0, -0.785, 0.5, 0.0]
    pos4: [1,1,0,0,0,0 ]

    joints:
      - FL_HAA
      - FR_HAA
      - FL_KFE
      - FL_HFE
      - FR_KFE
      - FR_HFE
